### ISSUE TITLE
error: name 'Raw_Input' is not defined

### ISSUE THREAD

**Issue by JamiePhonic** [EvanHahn/pushbullet-cli#12]
followinf a fresh install of python 3.4 and cygwin 32 bit, the pb command now returns this error:
`$ pb -a test
What's your API key?
Find it at <https://www.pushbullet.com/account>.
Traceback (most recent call last):
  File "C:\Apps\Python34\Scripts\pb-script.py", line 9, in <module>
  load_entry_point('Pushbullet-CLI==0.1', 'console_scripts', 'pb')()
  File "C:\Apps\Python34\lib\site-packages\pushbullet_cli-0.1-py3.4.egg\pushbullet_cli\app.py", line 117, in main
  File "C:\Apps\Python34\lib\site-packages\pushbullet_cli-0.1-py3.4.egg\pushbullet_cli\app.py", line 62, in _get_api_key
NameError: name 'raw_input' is not defined`

this is an issue with python 3 when "raw_input()" was changed to just "input()"

**Comment by r-darwish** [comment]
Should be resolved now
